name: Disaster-Alleviation-Foundation_$(Date:yyyyMMdd)$(Rev:r)
trigger:
- master
pool:
 vnImage: ubuntu-latest
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '''**/AllocateGoodsModelTests''.csproj'